//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package azopenai

// ChatRole - A description of the intended purpose of a message within a chat completions interaction.
type ChatRole string

const (
	ChatRoleAssistant ChatRole = "assistant"
	ChatRoleFunction  ChatRole = "function"
	ChatRoleSystem    ChatRole = "system"
	ChatRoleUser      ChatRole = "user"
)

// PossibleChatRoleValues returns the possible values for the ChatRole const type.
func PossibleChatRoleValues() []ChatRole {
	return []ChatRole{
		ChatRoleAssistant,
		ChatRoleFunction,
		ChatRoleSystem,
		ChatRoleUser,
	}
}

// CompletionsFinishReason - Representation of the manner in which a completions response concluded.
type CompletionsFinishReason string

const (
	CompletionsFinishReasonContentFilter CompletionsFinishReason = "content_filter"
	CompletionsFinishReasonFunctionCall  CompletionsFinishReason = "function_call"
	CompletionsFinishReasonLength        CompletionsFinishReason = "length"
	CompletionsFinishReasonStop          CompletionsFinishReason = "stop"
)

// PossibleCompletionsFinishReasonValues returns the possible values for the CompletionsFinishReason const type.
func PossibleCompletionsFinishReasonValues() []CompletionsFinishReason {
	return []CompletionsFinishReason{
		CompletionsFinishReasonContentFilter,
		CompletionsFinishReasonFunctionCall,
		CompletionsFinishReasonLength,
		CompletionsFinishReasonStop,
	}
}

// FunctionCallPreset - Preset values to control how the mode; responds to function calls.
type FunctionCallPreset string

const (
	FunctionCallPresetAuto FunctionCallPreset = "auto"
	FunctionCallPresetNone FunctionCallPreset = "none"
)

// PossibleFunctionCallPresetValues returns the possible values for the FunctionCallPreset const type.
func PossibleFunctionCallPresetValues() []FunctionCallPreset {
	return []FunctionCallPreset{
		FunctionCallPresetAuto,
		FunctionCallPresetNone,
	}
}

// ImageSize - The desired size of the generated images. Must be one of 256x256, 512x512, or 1024x1024.
type ImageSize string

const (
	ImageSize512x512   ImageSize = "512x512"
	ImageSize1024x1024 ImageSize = "1024x1024"
	ImageSize256x256   ImageSize = "256x256"
)

// PossibleImageSizeValues returns the possible values for the ImageSize const type.
func PossibleImageSizeValues() []ImageSize {
	return []ImageSize{
		ImageSize512x512,
		ImageSize1024x1024,
		ImageSize256x256,
	}
}

// State - The state of a job or item.
type State string

const (
	StateCanceled   State = "canceled"
	StateFailed     State = "failed"
	StateNotRunning State = "notRunning"
	StateRunning    State = "running"
	StateSucceeded  State = "succeeded"
)

// PossibleStateValues returns the possible values for the State const type.
func PossibleStateValues() []State {
	return []State{
		StateCanceled,
		StateFailed,
		StateNotRunning,
		StateRunning,
		StateSucceeded,
	}
}
