//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openai

const host = "https://api.openai.com/v1"

// ChatCompletionRequestMessageRole - The role of the messages author. One of system, user, assistant, or function.
type ChatCompletionRequestMessageRole string

const (
	ChatCompletionRequestMessageRoleAssistant ChatCompletionRequestMessageRole = "assistant"
	ChatCompletionRequestMessageRoleFunction  ChatCompletionRequestMessageRole = "function"
	ChatCompletionRequestMessageRoleSystem    ChatCompletionRequestMessageRole = "system"
	ChatCompletionRequestMessageRoleUser      ChatCompletionRequestMessageRole = "user"
)

// PossibleChatCompletionRequestMessageRoleValues returns the possible values for the ChatCompletionRequestMessageRole const type.
func PossibleChatCompletionRequestMessageRoleValues() []ChatCompletionRequestMessageRole {
	return []ChatCompletionRequestMessageRole{
		ChatCompletionRequestMessageRoleAssistant,
		ChatCompletionRequestMessageRoleFunction,
		ChatCompletionRequestMessageRoleSystem,
		ChatCompletionRequestMessageRoleUser,
	}
}

// ChatCompletionResponseMessageRole - The role of the author of this message.
type ChatCompletionResponseMessageRole string

const (
	ChatCompletionResponseMessageRoleAssistant ChatCompletionResponseMessageRole = "assistant"
	ChatCompletionResponseMessageRoleFunction  ChatCompletionResponseMessageRole = "function"
	ChatCompletionResponseMessageRoleSystem    ChatCompletionResponseMessageRole = "system"
	ChatCompletionResponseMessageRoleUser      ChatCompletionResponseMessageRole = "user"
)

// PossibleChatCompletionResponseMessageRoleValues returns the possible values for the ChatCompletionResponseMessageRole const type.
func PossibleChatCompletionResponseMessageRoleValues() []ChatCompletionResponseMessageRole {
	return []ChatCompletionResponseMessageRole{
		ChatCompletionResponseMessageRoleAssistant,
		ChatCompletionResponseMessageRoleFunction,
		ChatCompletionResponseMessageRoleSystem,
		ChatCompletionResponseMessageRoleUser,
	}
}

// ChatCompletionStreamResponseDeltaRole - The role of the author of this message.
type ChatCompletionStreamResponseDeltaRole string

const (
	ChatCompletionStreamResponseDeltaRoleAssistant ChatCompletionStreamResponseDeltaRole = "assistant"
	ChatCompletionStreamResponseDeltaRoleFunction  ChatCompletionStreamResponseDeltaRole = "function"
	ChatCompletionStreamResponseDeltaRoleSystem    ChatCompletionStreamResponseDeltaRole = "system"
	ChatCompletionStreamResponseDeltaRoleUser      ChatCompletionStreamResponseDeltaRole = "user"
)

// PossibleChatCompletionStreamResponseDeltaRoleValues returns the possible values for the ChatCompletionStreamResponseDeltaRole const type.
func PossibleChatCompletionStreamResponseDeltaRoleValues() []ChatCompletionStreamResponseDeltaRole {
	return []ChatCompletionStreamResponseDeltaRole{
		ChatCompletionStreamResponseDeltaRoleAssistant,
		ChatCompletionStreamResponseDeltaRoleFunction,
		ChatCompletionStreamResponseDeltaRoleSystem,
		ChatCompletionStreamResponseDeltaRoleUser,
	}
}

type CreateChatCompletionResponseChoicesItemFinishReason string

const (
	CreateChatCompletionResponseChoicesItemFinishReasonFunctionCall CreateChatCompletionResponseChoicesItemFinishReason = "function_call"
	CreateChatCompletionResponseChoicesItemFinishReasonLength       CreateChatCompletionResponseChoicesItemFinishReason = "length"
	CreateChatCompletionResponseChoicesItemFinishReasonStop         CreateChatCompletionResponseChoicesItemFinishReason = "stop"
)

// PossibleCreateChatCompletionResponseChoicesItemFinishReasonValues returns the possible values for the CreateChatCompletionResponseChoicesItemFinishReason const type.
func PossibleCreateChatCompletionResponseChoicesItemFinishReasonValues() []CreateChatCompletionResponseChoicesItemFinishReason {
	return []CreateChatCompletionResponseChoicesItemFinishReason{
		CreateChatCompletionResponseChoicesItemFinishReasonFunctionCall,
		CreateChatCompletionResponseChoicesItemFinishReasonLength,
		CreateChatCompletionResponseChoicesItemFinishReasonStop,
	}
}

type CreateChatCompletionStreamResponseChoicesItemFinishReason string

const (
	CreateChatCompletionStreamResponseChoicesItemFinishReasonFunctionCall CreateChatCompletionStreamResponseChoicesItemFinishReason = "function_call"
	CreateChatCompletionStreamResponseChoicesItemFinishReasonLength       CreateChatCompletionStreamResponseChoicesItemFinishReason = "length"
	CreateChatCompletionStreamResponseChoicesItemFinishReasonStop         CreateChatCompletionStreamResponseChoicesItemFinishReason = "stop"
)

// PossibleCreateChatCompletionStreamResponseChoicesItemFinishReasonValues returns the possible values for the CreateChatCompletionStreamResponseChoicesItemFinishReason const type.
func PossibleCreateChatCompletionStreamResponseChoicesItemFinishReasonValues() []CreateChatCompletionStreamResponseChoicesItemFinishReason {
	return []CreateChatCompletionStreamResponseChoicesItemFinishReason{
		CreateChatCompletionStreamResponseChoicesItemFinishReasonFunctionCall,
		CreateChatCompletionStreamResponseChoicesItemFinishReasonLength,
		CreateChatCompletionStreamResponseChoicesItemFinishReasonStop,
	}
}

type CreateCompletionResponseChoicesItemFinishReason string

const (
	CreateCompletionResponseChoicesItemFinishReasonLength CreateCompletionResponseChoicesItemFinishReason = "length"
	CreateCompletionResponseChoicesItemFinishReasonStop   CreateCompletionResponseChoicesItemFinishReason = "stop"
)

// PossibleCreateCompletionResponseChoicesItemFinishReasonValues returns the possible values for the CreateCompletionResponseChoicesItemFinishReason const type.
func PossibleCreateCompletionResponseChoicesItemFinishReasonValues() []CreateCompletionResponseChoicesItemFinishReason {
	return []CreateCompletionResponseChoicesItemFinishReason{
		CreateCompletionResponseChoicesItemFinishReasonLength,
		CreateCompletionResponseChoicesItemFinishReasonStop,
	}
}

type CreateEditResponseChoicesItemFinishReason string

const (
	CreateEditResponseChoicesItemFinishReasonLength CreateEditResponseChoicesItemFinishReason = "length"
	CreateEditResponseChoicesItemFinishReasonStop   CreateEditResponseChoicesItemFinishReason = "stop"
)

// PossibleCreateEditResponseChoicesItemFinishReasonValues returns the possible values for the CreateEditResponseChoicesItemFinishReason const type.
func PossibleCreateEditResponseChoicesItemFinishReasonValues() []CreateEditResponseChoicesItemFinishReason {
	return []CreateEditResponseChoicesItemFinishReason{
		CreateEditResponseChoicesItemFinishReasonLength,
		CreateEditResponseChoicesItemFinishReasonStop,
	}
}

// CreateImageEditRequestResponseFormat - The format in which the generated images are returned. Must be one of url or b64_json.
type CreateImageEditRequestResponseFormat string

const (
	CreateImageEditRequestResponseFormatB64JSON CreateImageEditRequestResponseFormat = "b64_json"
	CreateImageEditRequestResponseFormatURL     CreateImageEditRequestResponseFormat = "url"
)

// PossibleCreateImageEditRequestResponseFormatValues returns the possible values for the CreateImageEditRequestResponseFormat const type.
func PossibleCreateImageEditRequestResponseFormatValues() []CreateImageEditRequestResponseFormat {
	return []CreateImageEditRequestResponseFormat{
		CreateImageEditRequestResponseFormatB64JSON,
		CreateImageEditRequestResponseFormatURL,
	}
}

// CreateImageEditRequestSize - The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024.
type CreateImageEditRequestSize string

const (
	CreateImageEditRequestSizeFiveHundredTwelveX512      CreateImageEditRequestSize = "512x512"
	CreateImageEditRequestSizeOneThousandTwentyFourX1024 CreateImageEditRequestSize = "1024x1024"
	CreateImageEditRequestSizeTwoHundredFiftySixX256     CreateImageEditRequestSize = "256x256"
)

// PossibleCreateImageEditRequestSizeValues returns the possible values for the CreateImageEditRequestSize const type.
func PossibleCreateImageEditRequestSizeValues() []CreateImageEditRequestSize {
	return []CreateImageEditRequestSize{
		CreateImageEditRequestSizeFiveHundredTwelveX512,
		CreateImageEditRequestSizeOneThousandTwentyFourX1024,
		CreateImageEditRequestSizeTwoHundredFiftySixX256,
	}
}

// CreateImageRequestResponseFormat - The format in which the generated images are returned. Must be one of url or b64_json.
type CreateImageRequestResponseFormat string

const (
	CreateImageRequestResponseFormatB64JSON CreateImageRequestResponseFormat = "b64_json"
	CreateImageRequestResponseFormatURL     CreateImageRequestResponseFormat = "url"
)

// PossibleCreateImageRequestResponseFormatValues returns the possible values for the CreateImageRequestResponseFormat const type.
func PossibleCreateImageRequestResponseFormatValues() []CreateImageRequestResponseFormat {
	return []CreateImageRequestResponseFormat{
		CreateImageRequestResponseFormatB64JSON,
		CreateImageRequestResponseFormatURL,
	}
}

// CreateImageRequestSize - The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024.
type CreateImageRequestSize string

const (
	CreateImageRequestSizeFiveHundredTwelveX512      CreateImageRequestSize = "512x512"
	CreateImageRequestSizeOneThousandTwentyFourX1024 CreateImageRequestSize = "1024x1024"
	CreateImageRequestSizeTwoHundredFiftySixX256     CreateImageRequestSize = "256x256"
)

// PossibleCreateImageRequestSizeValues returns the possible values for the CreateImageRequestSize const type.
func PossibleCreateImageRequestSizeValues() []CreateImageRequestSize {
	return []CreateImageRequestSize{
		CreateImageRequestSizeFiveHundredTwelveX512,
		CreateImageRequestSizeOneThousandTwentyFourX1024,
		CreateImageRequestSizeTwoHundredFiftySixX256,
	}
}

// CreateImageVariationRequestResponseFormat - The format in which the generated images are returned. Must be one of url or
// b64_json.
type CreateImageVariationRequestResponseFormat string

const (
	CreateImageVariationRequestResponseFormatB64JSON CreateImageVariationRequestResponseFormat = "b64_json"
	CreateImageVariationRequestResponseFormatURL     CreateImageVariationRequestResponseFormat = "url"
)

// PossibleCreateImageVariationRequestResponseFormatValues returns the possible values for the CreateImageVariationRequestResponseFormat const type.
func PossibleCreateImageVariationRequestResponseFormatValues() []CreateImageVariationRequestResponseFormat {
	return []CreateImageVariationRequestResponseFormat{
		CreateImageVariationRequestResponseFormatB64JSON,
		CreateImageVariationRequestResponseFormatURL,
	}
}

// CreateImageVariationRequestSize - The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024.
type CreateImageVariationRequestSize string

const (
	CreateImageVariationRequestSizeFiveHundredTwelveX512      CreateImageVariationRequestSize = "512x512"
	CreateImageVariationRequestSizeOneThousandTwentyFourX1024 CreateImageVariationRequestSize = "1024x1024"
	CreateImageVariationRequestSizeTwoHundredFiftySixX256     CreateImageVariationRequestSize = "256x256"
)

// PossibleCreateImageVariationRequestSizeValues returns the possible values for the CreateImageVariationRequestSize const type.
func PossibleCreateImageVariationRequestSizeValues() []CreateImageVariationRequestSize {
	return []CreateImageVariationRequestSize{
		CreateImageVariationRequestSizeFiveHundredTwelveX512,
		CreateImageVariationRequestSizeOneThousandTwentyFourX1024,
		CreateImageVariationRequestSizeTwoHundredFiftySixX256,
	}
}

type Enum0 string

const (
	Enum0Gpt35Turbo        Enum0 = "gpt-3.5-turbo"
	Enum0Gpt35Turbo0613    Enum0 = "gpt-3.5-turbo-0613"
	Enum0Gpt35Turbo16K     Enum0 = "gpt-3.5-turbo-16k"
	Enum0Gpt35Turbo16K0613 Enum0 = "gpt-3.5-turbo-16k-0613"
	Enum0Gpt4              Enum0 = "gpt-4"
	Enum0Gpt40613          Enum0 = "gpt-4-0613"
	Enum0Gpt432K           Enum0 = "gpt-4-32k"
	Enum0Gpt432K0613       Enum0 = "gpt-4-32k-0613"
)

// PossibleEnum0Values returns the possible values for the Enum0 const type.
func PossibleEnum0Values() []Enum0 {
	return []Enum0{
		Enum0Gpt35Turbo,
		Enum0Gpt35Turbo0613,
		Enum0Gpt35Turbo16K,
		Enum0Gpt35Turbo16K0613,
		Enum0Gpt4,
		Enum0Gpt40613,
		Enum0Gpt432K,
		Enum0Gpt432K0613,
	}
}

type Enum14 string

const (
	Enum14TextEmbeddingAda002 Enum14 = "text-embedding-ada-002"
)

// PossibleEnum14Values returns the possible values for the Enum14 const type.
func PossibleEnum14Values() []Enum14 {
	return []Enum14{
		Enum14TextEmbeddingAda002,
	}
}

type Enum15 string

const (
	Enum15Whisper1 Enum15 = "whisper-1"
)

// PossibleEnum15Values returns the possible values for the Enum15 const type.
func PossibleEnum15Values() []Enum15 {
	return []Enum15{
		Enum15Whisper1,
	}
}

type Enum16 string

const (
	Enum16Whisper1 Enum16 = "whisper-1"
)

// PossibleEnum16Values returns the possible values for the Enum16 const type.
func PossibleEnum16Values() []Enum16 {
	return []Enum16{
		Enum16Whisper1,
	}
}

type Enum17 string

const (
	Enum17Ada     Enum17 = "ada"
	Enum17Babbage Enum17 = "babbage"
	Enum17Curie   Enum17 = "curie"
	Enum17Davinci Enum17 = "davinci"
)

// PossibleEnum17Values returns the possible values for the Enum17 const type.
func PossibleEnum17Values() []Enum17 {
	return []Enum17{
		Enum17Ada,
		Enum17Babbage,
		Enum17Curie,
		Enum17Davinci,
	}
}

type Enum18 string

const (
	Enum18TextModerationLatest Enum18 = "text-moderation-latest"
	Enum18TextModerationStable Enum18 = "text-moderation-stable"
)

// PossibleEnum18Values returns the possible values for the Enum18 const type.
func PossibleEnum18Values() []Enum18 {
	return []Enum18{
		Enum18TextModerationLatest,
		Enum18TextModerationStable,
	}
}

type Enum2 string

const (
	Enum2Auto Enum2 = "auto"
	Enum2None Enum2 = "none"
)

// PossibleEnum2Values returns the possible values for the Enum2 const type.
func PossibleEnum2Values() []Enum2 {
	return []Enum2{
		Enum2Auto,
		Enum2None,
	}
}

type Enum21 string

const (
	Enum21CodeDavinciEdit001 Enum21 = "code-davinci-edit-001"
	Enum21TextDavinciEdit001 Enum21 = "text-davinci-edit-001"
)

// PossibleEnum21Values returns the possible values for the Enum21 const type.
func PossibleEnum21Values() []Enum21 {
	return []Enum21{
		Enum21CodeDavinciEdit001,
		Enum21TextDavinciEdit001,
	}
}

type Enum5 string

const (
	Enum5CodeDavinci002 Enum5 = "code-davinci-002"
	Enum5TextAda001     Enum5 = "text-ada-001"
	Enum5TextBabbage001 Enum5 = "text-babbage-001"
	Enum5TextCurie001   Enum5 = "text-curie-001"
	Enum5TextDavinci001 Enum5 = "text-davinci-001"
	Enum5TextDavinci002 Enum5 = "text-davinci-002"
	Enum5TextDavinci003 Enum5 = "text-davinci-003"
)

// PossibleEnum5Values returns the possible values for the Enum5 const type.
func PossibleEnum5Values() []Enum5 {
	return []Enum5{
		Enum5CodeDavinci002,
		Enum5TextAda001,
		Enum5TextBabbage001,
		Enum5TextCurie001,
		Enum5TextDavinci001,
		Enum5TextDavinci002,
		Enum5TextDavinci003,
	}
}
