//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package openai

// APIClientCancelFineTuneResponse contains the response from method APIClient.CancelFineTune.
type APIClientCancelFineTuneResponse struct {
	FineTune
}

// APIClientCreateChatCompletionResponse contains the response from method APIClient.CreateChatCompletion.
type APIClientCreateChatCompletionResponse struct {
	CreateChatCompletionResponse
}

// APIClientCreateCompletionResponse contains the response from method APIClient.CreateCompletion.
type APIClientCreateCompletionResponse struct {
	CreateCompletionResponse
}

// APIClientCreateEditResponse contains the response from method APIClient.CreateEdit.
type APIClientCreateEditResponse struct {
	CreateEditResponse
}

// APIClientCreateEmbeddingResponse contains the response from method APIClient.CreateEmbedding.
type APIClientCreateEmbeddingResponse struct {
	CreateEmbeddingResponse
}

// APIClientCreateFileResponse contains the response from method APIClient.CreateFile.
type APIClientCreateFileResponse struct {
	File
}

// APIClientCreateFineTuneResponse contains the response from method APIClient.CreateFineTune.
type APIClientCreateFineTuneResponse struct {
	FineTune
}

// APIClientCreateImageEditResponse contains the response from method APIClient.CreateImageEdit.
type APIClientCreateImageEditResponse struct {
	ImagesResponse
}

// APIClientCreateImageResponse contains the response from method APIClient.CreateImage.
type APIClientCreateImageResponse struct {
	ImagesResponse
}

// APIClientCreateImageVariationResponse contains the response from method APIClient.CreateImageVariation.
type APIClientCreateImageVariationResponse struct {
	ImagesResponse
}

// APIClientCreateModerationResponse contains the response from method APIClient.CreateModeration.
type APIClientCreateModerationResponse struct {
	CreateModerationResponse
}

// APIClientCreateTranscriptionResponse contains the response from method APIClient.CreateTranscription.
type APIClientCreateTranscriptionResponse struct {
	CreateTranscriptionResponse
}

// APIClientCreateTranslationResponse contains the response from method APIClient.CreateTranslation.
type APIClientCreateTranslationResponse struct {
	CreateTranslationResponse
}

// APIClientDeleteFileResponse contains the response from method APIClient.DeleteFile.
type APIClientDeleteFileResponse struct {
	DeleteFileResponse
}

// APIClientDeleteModelResponse contains the response from method APIClient.DeleteModel.
type APIClientDeleteModelResponse struct {
	DeleteModelResponse
}

// APIClientDownloadFileResponse contains the response from method APIClient.DownloadFile.
type APIClientDownloadFileResponse struct {
	Value *string
}

// APIClientListFilesResponse contains the response from method APIClient.ListFiles.
type APIClientListFilesResponse struct {
	ListFilesResponse
}

// APIClientListFineTuneEventsResponse contains the response from method APIClient.ListFineTuneEvents.
type APIClientListFineTuneEventsResponse struct {
	ListFineTuneEventsResponse
}

// APIClientListFineTunesResponse contains the response from method APIClient.ListFineTunes.
type APIClientListFineTunesResponse struct {
	ListFineTunesResponse
}

// APIClientListModelsResponse contains the response from method APIClient.ListModels.
type APIClientListModelsResponse struct {
	ListModelsResponse
}

// APIClientRetrieveFileResponse contains the response from method APIClient.RetrieveFile.
type APIClientRetrieveFileResponse struct {
	File
}

// APIClientRetrieveFineTuneResponse contains the response from method APIClient.RetrieveFineTune.
type APIClientRetrieveFineTuneResponse struct {
	FineTune
}

// APIClientRetrieveModelResponse contains the response from method APIClient.RetrieveModel.
type APIClientRetrieveModelResponse struct {
	Model
}
