// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./checkpoint_store.go

// Package azeventhubs is a generated GoMock package.
package azeventhubs

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCheckpointStore is a mock of CheckpointStore interface.
type MockCheckpointStore struct {
	ctrl     *gomock.Controller
	recorder *MockCheckpointStoreMockRecorder
}

// MockCheckpointStoreMockRecorder is the mock recorder for MockCheckpointStore.
type MockCheckpointStoreMockRecorder struct {
	mock *MockCheckpointStore
}

// NewMockCheckpointStore creates a new mock instance.
func NewMockCheckpointStore(ctrl *gomock.Controller) *MockCheckpointStore {
	mock := &MockCheckpointStore{ctrl: ctrl}
	mock.recorder = &MockCheckpointStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckpointStore) EXPECT() *MockCheckpointStoreMockRecorder {
	return m.recorder
}

// ClaimOwnership mocks base method.
func (m *MockCheckpointStore) ClaimOwnership(ctx context.Context, partitionOwnership []Ownership, options *ClaimOwnershipOptions) ([]Ownership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimOwnership", ctx, partitionOwnership, options)
	ret0, _ := ret[0].([]Ownership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimOwnership indicates an expected call of ClaimOwnership.
func (mr *MockCheckpointStoreMockRecorder) ClaimOwnership(ctx, partitionOwnership, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimOwnership", reflect.TypeOf((*MockCheckpointStore)(nil).ClaimOwnership), ctx, partitionOwnership, options)
}

// ListCheckpoints mocks base method.
func (m *MockCheckpointStore) ListCheckpoints(ctx context.Context, fullyQualifiedNamespace, eventHubName, consumerGroup string, options *ListCheckpointsOptions) ([]Checkpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCheckpoints", ctx, fullyQualifiedNamespace, eventHubName, consumerGroup, options)
	ret0, _ := ret[0].([]Checkpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCheckpoints indicates an expected call of ListCheckpoints.
func (mr *MockCheckpointStoreMockRecorder) ListCheckpoints(ctx, fullyQualifiedNamespace, eventHubName, consumerGroup, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCheckpoints", reflect.TypeOf((*MockCheckpointStore)(nil).ListCheckpoints), ctx, fullyQualifiedNamespace, eventHubName, consumerGroup, options)
}

// ListOwnership mocks base method.
func (m *MockCheckpointStore) ListOwnership(ctx context.Context, fullyQualifiedNamespace, eventHubName, consumerGroup string, options *ListOwnershipOptions) ([]Ownership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOwnership", ctx, fullyQualifiedNamespace, eventHubName, consumerGroup, options)
	ret0, _ := ret[0].([]Ownership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOwnership indicates an expected call of ListOwnership.
func (mr *MockCheckpointStoreMockRecorder) ListOwnership(ctx, fullyQualifiedNamespace, eventHubName, consumerGroup, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOwnership", reflect.TypeOf((*MockCheckpointStore)(nil).ListOwnership), ctx, fullyQualifiedNamespace, eventHubName, consumerGroup, options)
}

// SetCheckpoint mocks base method.
func (m *MockCheckpointStore) SetCheckpoint(ctx context.Context, checkpoint Checkpoint, options *SetCheckpointOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCheckpoint", ctx, checkpoint, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCheckpoint indicates an expected call of SetCheckpoint.
func (mr *MockCheckpointStoreMockRecorder) SetCheckpoint(ctx, checkpoint, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCheckpoint", reflect.TypeOf((*MockCheckpointStore)(nil).SetCheckpoint), ctx, checkpoint, options)
}
