// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./processor.go

// Package azeventhubs is a generated GoMock package.
package azeventhubs

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockconsumerClientForProcessor is a mock of consumerClientForProcessor interface.
type MockconsumerClientForProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockconsumerClientForProcessorMockRecorder
}

// MockconsumerClientForProcessorMockRecorder is the mock recorder for MockconsumerClientForProcessor.
type MockconsumerClientForProcessorMockRecorder struct {
	mock *MockconsumerClientForProcessor
}

// NewMockconsumerClientForProcessor creates a new mock instance.
func NewMockconsumerClientForProcessor(ctrl *gomock.Controller) *MockconsumerClientForProcessor {
	mock := &MockconsumerClientForProcessor{ctrl: ctrl}
	mock.recorder = &MockconsumerClientForProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconsumerClientForProcessor) EXPECT() *MockconsumerClientForProcessorMockRecorder {
	return m.recorder
}

// GetEventHubProperties mocks base method.
func (m *MockconsumerClientForProcessor) GetEventHubProperties(ctx context.Context, options *GetEventHubPropertiesOptions) (EventHubProperties, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventHubProperties", ctx, options)
	ret0, _ := ret[0].(EventHubProperties)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventHubProperties indicates an expected call of GetEventHubProperties.
func (mr *MockconsumerClientForProcessorMockRecorder) GetEventHubProperties(ctx, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventHubProperties", reflect.TypeOf((*MockconsumerClientForProcessor)(nil).GetEventHubProperties), ctx, options)
}

// NewPartitionClient mocks base method.
func (m *MockconsumerClientForProcessor) NewPartitionClient(partitionID string, options *PartitionClientOptions) (*PartitionClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPartitionClient", partitionID, options)
	ret0, _ := ret[0].(*PartitionClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewPartitionClient indicates an expected call of NewPartitionClient.
func (mr *MockconsumerClientForProcessorMockRecorder) NewPartitionClient(partitionID, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPartitionClient", reflect.TypeOf((*MockconsumerClientForProcessor)(nil).NewPartitionClient), partitionID, options)
}

// getDetails mocks base method.
func (m *MockconsumerClientForProcessor) getDetails() consumerClientDetails {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getDetails")
	ret0, _ := ret[0].(consumerClientDetails)
	return ret0
}

// getDetails indicates an expected call of getDetails.
func (mr *MockconsumerClientForProcessorMockRecorder) getDetails() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getDetails", reflect.TypeOf((*MockconsumerClientForProcessor)(nil).getDetails))
}
