apiVersion: batch/v1
kind: Job
metadata:
  name: go-sb-stresstest
  namespace: ripark-awesome
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - env:
        - name: SERVICEBUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              key: SERVICEBUS_CONNECTION_STRING
              name: go-secret
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              key: APPINSIGHTS_INSTRUMENTATIONKEY
              name: go-secret
        image: stresstesttbiruti6oi24k.azurecr.io/ripark/gosbtest
        imagePullPolicy: Always
        command:
          - "/app/stress"
          - "tests"
          - "infiniteSendAndReceive"
        name: main
      restartPolicy: Never